### ISSUE TITLE
Compatibilidad con python 3.9

### ISSUE THREAD

**Issue by matiasrivera** [matbarofex/pyRofex#14]
Traceback (most recent call last):
  File "C:\Users\JJB\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\JJB\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\JJB\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_app.py", line 312, in run_forever
    teardown()
  File "C:\Users\JJB\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_app.py", line 231, in teardown
    if thread and thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

Aparentemente en python 3.9 el método isAlive de Thread se ha renombrado a is_alive

Por favor tener en cuenta para que la libreria sea compatible con la nueva release de python

**Comment by fzanuso** [comment]
Hola Matias, la verdad que no lo había probado con python 3.9 y tenes razón. Muchas gracias por el comentario. En principio no es algo que pueda cambiar directamente porque la incompatibilidad viene desde la librería websocket-client que utilizo para establecer la conexión. Voy a estar atento por si sacan una versión compatible con 3.9, sino tengo que ver de utilizar otro cliente websocket.

**Comment by rodrialbanese** [comment]
yo con 3.9 lo estoy usando.
lo unico que hice fue reemplazar la linea 231 en _app.py de la libreria del cliente de websocket
de
`if thread and thread.isAlive():`
a
`if thread and thread.is_alive():`

No sé si hay algun otro problema, yo hasta ahora no detecté nada.
el cliente websocket ya se actualizó para que se pueda usar en 3.9 (hace un tiempo) pero me parece que cambiaron algunas funciones y pyrofex manda cantidad incorrecta de argumentos y obviamente no funciona.
