### ISSUE TITLE
Problema con el websocket 

### ISSUE THREAD

**Issue by jcosentino1** [matbarofex/pyRofex#21]
Recibo el error ‘NoneType’ object has no attributte ‘connected’ al intentar suscribirme al websocket hasta el 29/09 anda perfectamente.

**Comment by jcosentino1** [comment]
Hola, inicialmente me daba ese error y ahora el error que recibo es:



Enviado desde un dispositivo móvil

**Comment by fplanas27** [comment]
a mi me da siempre:

import time

import pyRofex


# 1-Initialize the environment
pyRofex.initialize(user="fplanas5506",
                   password="nralwT8&",
                   account="REM5506",
                   environment=pyRofex.Environment.REMARKET)


# 2-Defines the handlers that will process the messages and exceptions.
def order_report_handler(message):
    print("Order Report Message Received: {0}".format(message))


def error_handler(message):
    print("Error Message Received: {0}".format(message))


def exception_handler(e):
    print("Exception Occurred: {0}".format(e.message))

pyRofex.init_websocket_connection(order_report_handler=order_report_handler,
                                  error_handler=error_handler,
                                  exception_handler=exception_handler)
Traceback (most recent call last):

  File "<ipython-input-2-3b147f5388ec>", line 1, in <module>
    pyRofex.init_websocket_connection(order_report_handler=order_report_handler,

  File "C:\Users\fplan\Anaconda3\envs\ArgyBondsBAF\lib\site-packages\pyRofex\service.py", line 443, in init_websocket_connection
    client.connect()

  File "C:\Users\fplan\Anaconda3\envs\ArgyBondsBAF\lib\site-packages\pyRofex\clients\websocket_rfx.py", line 134, in connect
    while not self.ws_connection.sock.connected and conn_timeout:

AttributeError: 'NoneType' object has no attribute 'connected'

**Comment by fplanas27** [comment]
Al querer hacer la conexion por websocket no arroja el error pero al sbscribir al order_report dice que la conexion ya esta cerrada.

import time

import pyRofex


# 1-Initialize the environment
pyRofex.initialize(user="xxxxxxx",
                   password="xxxxxxx",
                   account="xxxxxxxx",
                   environment=pyRofex.Environment.REMARKET)


# 2-Defines the handlers that will process the messages and exceptions.
def order_report_handler(message):
    print("Order Report Message Received: {0}".format(message))


def error_handler(message):
    print("Error Message Received: {0}".format(message))

"""
def exception_handler(e):
    print("Exception Occurred: {0}".format(e.message))
"""

# 3-Initialize Websocket Connection with the handlers
pyRofex.init_websocket_connection(order_report_handler=order_report_handler,
                                  error_handler=error_handler)

pyRofex.order_report_subscription()
Traceback (most recent call last):

  File "<ipython-input-18-352682cd9188>", line 1, in <module>
    pyRofex.order_report_subscription()

  File "C:\Users\fplan\Anaconda3\envs\ArgyBondsBAF\lib\site-packages\pyRofex\service.py", line 574, in order_report_subscription
    client.order_report_subscription(account, snapshot)

  File "C:\Users\fplan\Anaconda3\envs\ArgyBondsBAF\lib\site-packages\pyRofex\clients\websocket_rfx.py", line 262, in order_report_subscription
    self.ws_connection.send(message)

  File "C:\Users\fplan\Anaconda3\envs\ArgyBondsBAF\lib\site-packages\websocket\_app.py", line 155, in send
    raise WebSocketConnectionClosedException(

WebSocketConnectionClosedException: Connection is already closed.

**Comment by fzanuso** [comment]
Hola fplanas27 , 

No estoy pudiendo reproducir el issue de mi lado. Entiendo por lo que decis que no te tira mas el error: **"AttributeError: 'NoneType' object has no attribute 'connected'"** pero ahora te esta tirando "WebSocketConnectionClosedException: Connection is already closed."

Ese error lo esta tirando porque esta intentando enviar un msj por la conexion websocket pero esta cerrada.

Que version de la libreria estas utilizando? podrias hacer: `pip show pyRofex`

**Comment by Aonik10** [comment]
Buenas, dos cosas que me pasaron a ver si ayuda para el fix.

Primero que nada, al exception_handler(e), le tuve que sacar el ".message" porque el error que recibo no tiene un atributo "message".

Hecho esto, el error que recibo tiene que ver con un problema de certificados:

Exception Occurred: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)
Exception Occurred: Connection could not be established.
Exception Occurred: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)
Exception Occurred: Connection could not be established.

Esto seguramente tiene que ver con el vencimiento global de certificados que hubo el 30/09/2021.

Esto lo podes corregir desde la librería o es un tema de cada uno?

**Comment by fzanuso** [comment]
**fplanas27** hay que importar el paquete ssl al inicio

`import ssl`

**Comment by fplanas27** [comment]
Ahi anduvo perfecto.

Te agradezco.


Federico Planas
***@***.***

**Comment by jcosentino1** [comment]
Hola, ahi probe con la version nueva incluyendo el parametro para evitar la validación, pero en el entorno LIVE no me toma ese parametro. Esto solo es para REMARKET?

Enviado desde un dispositivo móvil

**Comment by fplanas27** [comment]
Hola fzanuso,
   como estas?
estoy volviendo a tener el mismo problema desde varias maquinas:

DefaultVerifyPaths(cafile=None, capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='C:\\Program Files\\Common Files\\SSL/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='C:\\Program Files\\Common Files\\SSL/certs')
Traceback (most recent call last):

  File "C:\Users\fplan\OneDrive\Documentos\Python Scripts\APIRofex\pyRofexWebsocketOrderReport.py", line 60, in <module>
    pyRofex.order_report_subscription()

  File "C:\Users\fplan\Anaconda3\envs\ISM\lib\site-packages\pyRofex\service.py", line 579, in order_report_subscription
    client.order_report_subscription(account, snapshot)

  File "C:\Users\fplan\Anaconda3\envs\ISM\lib\site-packages\pyRofex\clients\websocket_rfx.py", line 264, in order_report_subscription
    self.ws_connection.send(message)

  File "C:\Users\fplan\Anaconda3\envs\ISM\lib\site-packages\websocket\_app.py", line 155, in send
    raise WebSocketConnectionClosedException(

WebSocketConnectionClosedException: Connection is already closed.


pip show pyRofex
Name: pyRofex
Version: 0.4.2rc1
Summary: Python connector for ROFEX's Rest and Websocket APIs.
Home-page: https://github.com/gruporofex/pyRofex
Author: Franco Zanuso
Author-email: francozanuso89@gmail.com
License: UNKNOWN
Location: c:\users\fplan\anaconda3\envs\ism\lib\site-packages
Requires: enum34, requests, simplejson, websocket-client
Required-by: 
Note: you may need to restart the kernel to use updated packages.
